import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#8f4538",
        "on-error-container": "#93000a",
        "surface-container-highest": "#eae1d7",
        "on-tertiary-fixed-variant": "#434936",
        "secondary-fixed": "#d9eaa3",
        "surface-container-low": "#fbf2e8",
        "tertiary-container": "#707661",
        "on-surface-variant": "#544340",
        "inverse-on-surface": "#f8efe5",
        "tertiary-fixed": "#dfe5cc",
        "primary-container": "#ad5d4e",
        "surface-tint": "#93493b",
        "surface-container-high": "#f0e7dd",
        "on-tertiary": "#ffffff",
        outline: "#87726f",
        "on-surface": "#1f1b15",
        "surface-container": "#f6ece3",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#f8fee4",
        surface: "#fff8f3",
        "on-secondary-fixed-variant": "#3e4c16",
        secondary: "#56642b",
        "secondary-fixed-dim": "#bdce89",
        "on-secondary": "#ffffff",
        "on-background": "#1f1b15",
        "inverse-surface": "#343029",
        "surface-dim": "#e1d9cf",
        "on-primary-container": "#fffaf9",
        "tertiary-fixed-dim": "#c3c9b1",
        "on-secondary-fixed": "#161f00",
        "secondary-container": "#d6e7a1",
        "inverse-primary": "#ffb4a6",
        "primary-fixed-dim": "#ffb4a6",
        background: "#fff8f3",
        tertiary: "#575d4a",
        "surface-variant": "#eae1d7",
        "primary-fixed": "#ffdad3",
        "on-primary-fixed-variant": "#763226",
        "on-primary-fixed": "#3c0702",
        "on-tertiary-fixed": "#181d0e",
        "surface-bright": "#fff8f3",
        "on-error": "#ffffff",
        "outline-variant": "#dac1bd",
        error: "#ba1a1a",
        "on-secondary-container": "#5a682f",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        // "Command" theme — dark, field-ready. Scoped to /tools (see .command-theme).
        cmd: {
          bg: "#0B0F0A",
          surface: "#121711",
          surface2: "#181F15",
          line: "#26301C",
          "line-strong": "#3A4A2A",
          text: "#E6EEDD",
          muted: "#8B9880",
          accent: "#A3E635",
          "accent-strong": "#BEF264",
          "accent-dim": "#65A30D",
          amber: "#F59E0B",
          info: "#7DD3FC",
          danger: "#F87171",
          "on-accent": "#0B0F0A",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "20px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-md": ["var(--font-bricolage)", "sans-serif"],
        "headline-lg": ["var(--font-bricolage)", "sans-serif"],
        "label-sm": ["var(--font-bricolage)", "sans-serif"],
        "body-lg": ["var(--font-bricolage)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-bricolage)", "sans-serif"],
        "body-md": ["var(--font-bricolage)", "sans-serif"],
        "headline-md": ["var(--font-bricolage)", "sans-serif"],
        display: ["var(--font-bricolage)", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
